nandorojo/solito

docs/docs/starter.md

Added a new query param to the deploy button URL that can be used to select the app in `apps/next` in the created Vercel project, it will also allow the first deployment to work.

Add `root-directory` config to deploy button

---

example-monorepos/blank/packages/app/features/home/screen.tsx

The link to your twitter doesn't work on mobile when its a text element. This also serves as an example of linking to a website so I think it makes sense to update.
Basically just updated the home page template to use A from dripsy instead of Text.

fix: link on home screen in template

---

docs/docs/resources.mdx

The dripsy.com url currently used redirects to some email marketing service.

Fix dripsy URL

---

docs/docs/usage/text-link.mdx

correct closing tags for TextLink examples

---

example-monorepos/blank/apps/expo/metro.config.js
example-monorepos/blank/apps/expo/package.json
example-monorepos/blank/yarn.lock

as discussed in [Solito Issue #32](https://github.com/nandorojo/solito/issues/32) `metro-minify-esbuild` causes android builds (didn't test on IOS) to result in a blank screen app
https://user-images.githubusercontent.com/37480915/160510233-defaee67-c770-41d8-a487-795797162691.mp4
removing this dependency fixed the problem for me

fix: removed metro-minify-esbuild from expo project

---

example-monorepos/blank/packages/app/provider/navigation/index.tsx

`NavigationProvider` should allow ReactNodes to be passed as children, not just as ReactElements
eg.
```
import { PropsWithChildren} from 'react'
function Providers(children: PropsWithChildren<unknown>) {
return <NavigationProvider>{ children }</NavigationProvider>
}
```

[Example] Update NavigationProvider typeof children

---

src/router/use-navigation.ts

**Overview**
fixes an issue (Issue #58) where using back() from useRouter doesn't work from a component instantiated between the NavigationContainer and the Navigators.

:bug: Ensure useRouter back() works with container

---

example-monorepos/blank/apps/next/next.config.js
example-monorepos/blank/apps/next/package.json
example-monorepos/blank/packages/app/features/home/screen.tsx
example-monorepos/blank/yarn.lock

Got the following tff error for expo vector icon in next:
After this fix:
Next:
Expo
Expo vector icon seems like a common use case as it comes with Expo. Not sure if we should include this in the template or maybe just link this as optional setup in doc?

Next Config for Expo vector icon

---

create-solito-app/index.ts

Hey, firstly thanks for making Solito!
I was checking out the new tailwind template and ran 
`npx create-solito-app@latest my-solito-app -t with-tailwind`
It ended up cloning the blank template instead 👀
I checked and it seems two things were going on:
1- Template option not passed to `downloadAndExtractExample()` 
2- The short version of the flag is not parsed by commander. It seems the short version has to come first when declaring the option (weird...) [[docs examples](https://github.com/tj/commander.js/#common-option-types-boolean-and-value)]

Fix CLI template option

---

example-monorepos/with-tailwind/apps/next/tailwind.config.js

This is actually a bug in the example that I missed. Tailwind requires you to import its plugins

Update with-tailwind example

---

example-monorepos/blank/readme.md
example-monorepos/with-custom-font/readme.md
example-monorepos/with-expo-router/apps/expo/index.js
example-monorepos/with-expo-router/apps/expo/package.json
example-monorepos/with-expo-router/readme.md

Two updates for your review:
(1) Update starters readme to reflect the update to Expo 46 (from Expo 44 for some starters).
(2) For expo-router starter, the current setup only works for iOS and web. When running the app on Android, this error occurred:
```
Error: Unable to resolve module ./node_modules/expo-router/entry from /Users/ammarfaris/Developer/sandbox/solito-expo-router/apps/expo/ ...
```
After comparing against Evan Bacon's quick start (https://expo.github.io/router/docs/intro/), the quick start says to move the entry point from `apps/expo/package.json` and explicitly import it in `apps/expo/index.js`. Doing this, I am now able to successfully run the app across Android, iOS and web without the error above. 
Note: 
In Evan Bacon's example, he also include another import in …

update starters readme and expo-router entry

---

src/params/index.tsx
src/params/use-router.ts
src/params/use-router.web.ts

calling useRouter hook when using nextjs 13 branch leads to an error on expo: unable to find Navigation, instead of simply returning undefined. Using same method as use-route for use-router bypasses this issue so that useRouter hook is only called iff on web.

fix useRouter error for expo nextjs 13

---

package.json
src/link/core.tsx
src/link/use-custom-link.tsx
src/router/replace-helpers.ts
src/router/replace-helpers.web.ts
src/router/use-router.ts

Second attempt at #70.
Released in `1.1.2`.
Also available in version `2.0.0-canary.4`.
```sh
yarn add solito@next13
```
With `useRouter`:
```ts
router.replace('/', undefined, {
experimental: {
nativeBehavior: 'stack-replace',
isNestedNavigator: true
}
})
```
And with `Link`:
```tsx
<Link
replace
experimental={{ nativeBehavior: 'stack-replace', isNestedNavigator: true }}
/>
```

Add Stack replacement to `replace()`

---

example-monorepos/blank/apps/next/package.json
example-monorepos/with-custom-font/apps/next/package.json
example-monorepos/with-expo-router/apps/next/package.json
example-monorepos/with-tailwind/apps/next/package.json

Resolves #299 
Deploying the Tailwind Starter repo on Vercel fails when using node version 18.x. This will override the Vercel projects node version setting to use 16.x, fixing the build failures.

Adds Engine Version to Tailwind Starter Repo

---

example-monorepos/blank/apps/expo/metro.config.js
example-monorepos/with-custom-font/apps/expo/metro.config.js
example-monorepos/with-expo-router/apps/expo/metro.config.js
example-monorepos/with-tailwind/apps/expo/metro.config.js

- Closes #336
- Tailwind CSS starter does not support a 2nd Tailwind CSS / Next.js app in the monorepo due to phantom dependencies issues.
- Specifically: ["invalid hook calls / version of React"](https://reactjs.org/warnings/invalid-hook-call-warning.html) error when running `yarn native` after installing a 2nd Next.js + Tailwind CSS app into the directory.
- The `yarn native` command runs successfully and shares code with the `yarn web` command (i.e. fast refresh works when updating a Tailwind CSS class).
- Matches recommended setup of `metro.config.js` from Expo and Vercel:
- https://docs.expo.dev/guides/monorepos/#modify-the-metro-config
- https://github.com/vercel/turbo/blob/main/examples/with-react-native-web/apps/native/metro.config.js
✅ fix(examples): add missing line …

Add line to `metro.config.js` suggested for Expo monorepos

---

docs/docs/recipes/deploying.mdx
docs/sidebars.js

The default Expo Github Action to deploy doesn't work in a monorepo, but by adding one property to the action it does. I thought this might be helpful for others wishing to deploy both mobile and web at the same time.
Apologies for anything I missed when attempting to contribute.
_Result from a Solito project_

Recipe: EAS Update in a monorepo

---

example-monorepos/with-tailwind/apps/next/package.json
example-monorepos/with-tailwind/yarn.lock

Current yarn.lock file that is gitted into the repo for the tailwind monorepo example is inconsisent with it's package.json.
This caused a weird css behavior where the resulting css output differs from during dev (`yarn next`) and from build (`yarn build & yarn start`). I'll attach screenshots below.
Minor bump to next.js will fix this issue.
Screenshot: css issue after clean yarn.lock and showing build version
Screenshot: css fixed after next.js bump and showing build version

Fix with-tailwind monorepo example

---

example-monorepos/with-custom-font/apps/next/pages/_document.tsx

fix(examples): add `customFontCss` back to `document.tsx` in `solito / example-monorepos / with-custom-font / apps / next / pages /` and change extension from `.js` back to `.tsx`
This regression appears to have been committed as part of Solito 3.1 updates 😄

`customFontCss` missing in "with-custom-font" example monorepo

---

src/image/expo/image.web.tsx
src/image/image.types.ts

This PR changes the default image props to use expo image and adds [Expo Image Content Fit](https://docs.expo.dev/versions/unversioned/sdk/image/#contentfit) to available props for SolitoImage. contentFit will eventually replace  resizeMode as [resizeMode is deprecated](https://docs.expo.dev/versions/unversioned/sdk/image/#resizemode). For now, if contentFit is defined it will take precedence over resizeMode.

Add contentFit prop to SolitoImage

---

example-monorepos/blank/apps/expo/package.json
example-monorepos/blank/packages/app/features/home/screen.tsx
example-monorepos/blank/yarn.lock

The current blank example project had two minor issues, in particular it has a [missing dependency to `expo-image`](https://github.com/nandorojo/solito/issues/395#issuecomment-1591356890).
I guess the same error goes for the other examples but I havent tested it so I can't tell.

Example repo doesn't build on vercel

---

docs/docs/usage/image.mdx
src/image/expo/image.tsx
src/image/expo/image.web.tsx
src/image/fast/fast.tsx
src/image/image.types.ts
src/image/use-solito-image.ts

Quick change that was helpful for me, so it could probably be as well for others.
Add an `onError` props to `SolitoImage` as all image libraries used behind it support it.
P.S: Thanks for solito 🙌

feat: Add `onError` to image

---

src/image/image.types.ts

Just add the props `transition` and `recyclingKey` to `Image`, only on mobile, useful to reuse the component.
Especially with librairies like [FlashList](https://shopify.github.io/flash-list/).

feat(image): Add expo transtion & recyclingKey to props

---

src/router/replace-helpers.ts

The new arch and react-native 0.76 expose file correctly

Linking context exported on new Arch
